import sampleTrait from './sample.trait';
import expTextAreaTrait from './text-area.trait';
import expDataSourceTrait from './data-source.tait';
import expImageTrait from './image';
import expTitleSectionTrait from './title-section.trait';
import { TraitInterface } from '../../interfaces/trait.interface';
import expZigZagBannerTrait from './banner-with-image-layout.trait';
import expContentLibraryTrait from './content-library.trait';
import expLandingBannerTrait from './landing-banner.trait';
import expColorPickerTrait from './color-picker.trait';
import expSmallTwoColBannerTrait from './small-two-column.trait';
import expProductCardTrait from './product-card';
import expHtmlInputTrait from './html-input.trait';
import expTitleSectionLayout2Trait from './title-section-layout-2';
import expProductCardWithTitleImageTrait from './product-card-with-title-image-trait';
import expCTABannerTrait from './cta-banner.trait';
import expBlogCardTrait from './blog-trait';
import expImageSelectorTrait from './image-selector.trait';
import expRichTextEditor from './rich-text-editor';
import experroStorefront from './experro-storefront.trait';
import expRecommendationWidgetTrait from './recommendation-trait/recommendation-widget';
import expFormBuilderTrait from './form-builder/form-builder';
import expProductCardWithTabsTrait from './product-card-with-tabs/product-card-with-tabs';

const traits: Array<TraitInterface> = [];
traits.push(sampleTrait);
traits.push(expZigZagBannerTrait);
traits.push(expTextAreaTrait);
traits.push(expImageTrait);
traits.push(expDataSourceTrait);
traits.push(expTitleSectionTrait);
traits.push(expCTABannerTrait);
traits.push(expContentLibraryTrait);
traits.push(expLandingBannerTrait);
traits.push(expColorPickerTrait);
traits.push(expSmallTwoColBannerTrait);
traits.push(expProductCardTrait);
traits.push(expHtmlInputTrait);
traits.push(expTitleSectionLayout2Trait);
traits.push(expProductCardWithTitleImageTrait);
traits.push(expBlogCardTrait);
traits.push(expRichTextEditor);
traits.push(expImageSelectorTrait);
traits.push(experroStorefront);
traits.push(expRecommendationWidgetTrait);
traits.push(expFormBuilderTrait);
traits.push(expProductCardWithTabsTrait);
export default traits;
